services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: dbbookflight
      POSTGRES_USER: dbbookflight_user
      POSTGRES_PASSWORD: RjAfoKWWt0Zk7jG4atM9EdYfdvJiVuRy
    ports:
      - "5432:5432"
    networks:
      - app-net
    volumes:
      - db_data:/var/lib/postgresql/data

  js-flightservice:
    build:
      context: ./backend/FlightService
      dockerfile: Dockerfile
    restart: unless-stopped
    init: true
    env_file:
      - ./backend/FlightService/.env
    ports:
      - "12877:12877"
    networks:
      - app-net
    depends_on:
      - db

  js-frontend-book-flight-project:
    build:
      context: ./frontend-book-flight-project
      dockerfile: Dockerfile
    restart: unless-stopped
    init: true
    env_file:
      - ./frontend-book-flight-project/.env
    ports:
      - "4173:4173"
    networks:
      - app-net
    depends_on:
      - js-flightservice

networks:
  app-net:
    driver: bridge

volumes:
  db_data:
