name: Flights CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      PORT: ${{ secrets.PORT }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install
        working-directory: backend/FlightService

      - name: Start server in background
        run: npm start &
        working-directory: backend/FlightService

      - name: Wait for server to be ready
        run: npx wait-on http://localhost:12877/flights
        working-directory: backend/FlightService

      - name: Run Test
        run: npm test
        working-directory: backend/FlightService
